CONSOLE_NONE=0;CONSOLE_ERROR=1;CONSOLE_WARN=2;CONSOLE_INFO=3;CONSOLE_DEBUG=4;CONSOLE_LOG=5;CONSOLE_ALL=9;var P=function(a){function b(A){return function(){d!==0&&c&&c[A]&&c[A].apply(c,arguments)}}function e(A,k){return function(){var D=Array.prototype.slice.call(arguments);h.push([A].concat(D));c[A]||(A=
"log");if(o&&(q||!c||!c.log))o.apply(a,arguments);if(c&&(d>0?d>k:g.length+d<=k))try{if(c.apply)if(n)c[A].call(c,p+D.join(" "));else{D.splice(0,0,p);c[A].apply(c,D)}else c[A](p+D.join(" "))}catch(C){}}}var d=CONSOLE_NONE,c=a.console||{},n=/(iphone|ipad|ipod|android)/.test(navigator.userAgent.toLowerCase()),j={},h=[],o,q,p,g=["error","warn","info","debug","log"],t="assert clear count dir dirxml exception group groupCollapsed groupEnd profile profileEnd table time timeEnd trace".split(" "),w=0,r=0,z;
c.clear&&c.clear();for(r=t.length;w<r;w++){z=t[w];j[z]=b(z)}w=0;for(r=g.length;w<r;w++){z=g[w];j[z]=e(z,w)}j.getLogs=function(){return h};j.setCallback=function(A,k){o=A;q=!!k};j.setLevel=function(A){d=Number(A)};j.setPrefix=function(A){p=A};return j}(window);window.debug=P;(function(a){function b(Y,T){var Q=/^\w+\:\/\//,ga;if(typeof Y!=c)Y="";if(typeof T!=c)T="";ga=(Q.test(Y)?"":T)+Y;return(Q.test(ga)?"":ga.charAt(0)==="/"?ca:W)+ga}function e(Y,T){function Q(f,S){if(f[o]&&f[o]!==w&&f[o]!=="loaded"||S[r])return u;f[D]=f[k]=s;return x}function ga(f,S,V){if((V=!!V)||
Q(f,S)){S[r]=x;for(var R in za)if(za[C](R)&&!za[R][r])return;Ab=x;Da()}}function oa(f){if(ba.call(f[p])===m){f[p]();f[p]=s}}function ea(f,S){if(Q(f,S)){S[q]=x;X(function(){F[S[z]].removeChild(f);oa(S)},0)}}function U(f,S){if(f[o]===4){f[k]=l;S[q]=x;X(function(){oa(S)},0)}}function Nb(f,S,V,R,G,da){var Ja=f[z];X(function(){if("item"in F[Ja]){if(!F[Ja][0]){X(arguments.callee,25);return}F[Ja]=F[Ja][0]}var Ea=O.createElement(h);if(typeof V==c)Ea.type=V;if(typeof R==c)Ea.charset=R;if(ba.call(G)===m){Ea[D]=
Ea[k]=function(){G(Ea,f)};Ea.src=S;if(aa)Ea.async=u}F[Ja].insertBefore(Ea,Ja===n?F[Ja].firstChild:s);if(typeof da==c){Ea.text=da;ga(Ea,f,x)}},0)}function Bb(f,S,V,R){I[f[g]]=x;Nb(f,S,V,R,ga)}function ta(f,S,V,R){var G=arguments;if(Fa&&f[q]==s){f[q]=u;Nb(f,S,i,R,ea)}else if(!Fa&&f[q]!=s&&!f[q])f[p]=function(){ta.apply(s,G)};else Fa||Bb.apply(s,G)}function pa(f,S,V,R){var G=arguments,da;if(Fa&&f[q]==s){f[q]=u;da=f.xhr=fa?new fa("Microsoft.XMLHTTP"):new a.XMLHttpRequest;da[k]=function(){U(da,f)};da.open("GET",
S);da.send("")}else if(!Fa&&f[q]!=s&&!f[q])f[p]=function(){pa.apply(s,G)};else if(!Fa){I[f[g]]=x;Nb(f,S,V,R,s,f.xhr.responseText);f.xhr=s}}function ua(f){if(f.allowDup==s)f.allowDup=T.dupe;var S=f.type,V=f.charset,R=f.allowDup;f=b(f.src,Ob);var G=b(f).indexOf(ca)===0;if(typeof V!=c)V=s;R=!!R;if(R=!R){if(!(R=I[f]!=s)){if(!(R=Fa&&za[f]))a:{for(var da=-1;R=H[++da];)if(typeof R.src==c&&f===b(R.src)&&R.type!==i){R=x;break a}R=u}R=R}R=R}if(R)za[f]!=s&&za[f][q]&&!za[f][r]&&G&&ga(s,za[f],x);else{if(za[f]==
s)za[f]={};R=za[f];if(R[z]==s)R[z]=Pb;R[r]=u;R[g]=f;na=x;if(!ub&&Qb&&G)pa(R,f,S,V);else!ub&&dc?ta(R,f,S,V):Bb(R,f,S,V)}}function Xa(f){Y&&!ub&&Cb.push(f);if(!Y||Ka)f()}function Rb(f){var S=[],V;for(V=-1;++V<f.length;)if(ba.call(f[V])===v)S=S.concat(Rb(f[V]));else S[S.length]=f[V];return S}Y=!!Y;if(T==s)T=K;var Ab=u,Ka=Y&&T[t],dc=Ka&&T.cache,ub=Ka&&T.order,Qb=Ka&&T.xhr,uc=T[A],Pb=T.which,Ob=T.base,Da=l,na=u,Db,Fa=x,za={},Cb=[],va=s;Ka=dc||Qb||ub;Db={script:function(){B(va);var f=Rb(arguments),S=Db,
V;if(uc)for(V=-1;++V<f.length;){if(V===0)Xa(function(){ua(typeof f[0]==c?{src:f[0]}:f[0])});else S=S.script(f[V]);S=S.wait()}else Xa(function(){for(V=-1;++V<f.length;)ua(typeof f[V]==c?{src:f[V]}:f[V])});va=X(function(){Fa=u},5);return S},wait:function(f){B(va);Fa=u;ba.call(f)===m||(f=l);var S=e(x,T),V=S.trigger,R=function(){try{f()}catch(da){}V()};delete S.trigger;var G=function(){if(na&&!Ab)Da=R;else R()};Y&&!na?Cb.push(G):Xa(G);return S}};if(Y)Db.trigger=function(){for(var f,S=-1;f=Cb[++S];)f();
Cb=[]};return Db}function d(Y){var T,Q={},ga={UseCachePreload:"cache",UseLocalXHR:"xhr",UsePreloading:t,AlwaysPreserveOrder:A,AllowDuplicates:"dupe"},oa={AppendTo:z,BasePath:"base"};for(T in ga)oa[T]=ga[T];Q.order=!!K.order;for(T in oa)if(oa[C](T)&&K[oa[T]]!=s)Q[oa[T]]=Y[T]!=s?Y[T]:K[oa[T]];for(T in ga)if(ga[C](T))Q[ga[T]]=!!Q[ga[T]];if(!Q[t])Q.cache=Q.order=Q.xhr=u;Q.which=Q.which===n||Q.which===j?Q.which:n;return Q}var c="string",n="head",j="body",h="script",o="readyState",q="preloaddone",p="loadtrigger",
g="srcuri",t="preload",w="complete",r="done",z="which",A="preserve",k="onreadystatechange",D="onload",C="hasOwnProperty",i="script/cache",m="[object Function]",v="[object Array]",s=null,x=true,u=false,O=a.document,fa=a.ActiveXObject,X=a.setTimeout,B=a.clearTimeout,ba=Object.prototype.toString,l=function(){},F={},I={},W=/^[^?#]*\//.exec(a.location.href)[0],ca=/^\w+\:\/\/\/?[^\/]+/.exec(W)[0],H=O.getElementsByTagName(h),L=a.opera&&ba.call(a.opera)=="[object Opera]",J="MozAppearance"in O.documentElement.style,
aa=O.createElement(h).async===true,K={cache:!(J||L),order:J||L||aa,xhr:x,dupe:x,base:"",which:n};K[A]=u;K[t]=x;F[n]=O.head||O.getElementsByTagName(n);F[j]=O.getElementsByTagName(j);a.$LAB={setGlobalDefaults:function(Y){K=d(Y)},setOptions:function(Y){return e(u,d(Y))},script:function(){return e().script.apply(s,arguments)},wait:function(){return e().wait.apply(s,arguments)}};(function(Y,T,Q){if(O[o]==s&&O[Y]){O[o]="loading";O[Y](T,Q=function(){O.removeEventListener(T,Q,u);O[o]=w},u)}})("addEventListener",
"DOMContentLoaded")})(window);(function(){var a=false,b=/xyz/.test(function(){})?/\b_super\b/:/.*/;this.MingClass=function(){};MingClass.extend=function(e){function d(){!a&&this.init&&this.init.apply(this,
arguments)}var c=this.prototype;a=true;var n=new this;a=false;for(var j in e)n[j]=typeof e[j]=="function"&&typeof c[j]=="function"&&b.test(e[j])?function(h,o){return function(){var q=this._super;this._super=c[h];var p=o.apply(this,arguments);this._super=q;return p}}(j,e[j]):e[j];d.prototype=n;d.constructor=d;d.extend=arguments.callee;return d}})();XHR=function(){function a(e){try{return JSON.parse(e)}catch(d){return e}}function b(e,d,c,n,j,h){var o=/^(\w+:)?\/\/([^\/?#]+)/.exec(d);o=o&&(o[1]&&o[1].toLowerCase()!==location.protocol||o[2].toLowerCase()!==location.host);var q=window.XDomainRequest&&o?new XDomainRequest:window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");if(h==="script"&&e==="GET"&&o){var p=document.getElementsByTagName("head")[0]||
document.documentElement,g=document.createElement("script"),t=false;g.src=d;g.onload=g.onreadystatechange=function(){if(!t&&(!this.readyState||this.readyState==="loaded"||this.readyState==="complete")){t=true;g.onload=g.onreadystatechange=null;p&&g.parentNode&&p.removeChild(g)}};p.insertBefore(g,p.firstChild);return true}q.open(e,d,!!n);if(q.setRequestHeader){q.setRequestHeader("Content-Type","application/x-www-form-urlencoded");o||q.setRequestHeader("X-Requested-With","XMLHttpRequest")}if(j)q.withCredentials=
true;if(n)q.onreadystatechange=function(){q.readyState===4&&n.call(q,a(q.responseText),q.status)};q.send(c);return n?true:a(q.responseText)}this.get=function(e,d){return b("GET",e,null,d)};this.getWithCredentials=function(e,d){return b("GET",e,null,d,true)};this.getJson=function(e,d){return b("GET",e,null,null,d,"script")};this.post=function(e,d,c){return b("POST",e,d,c)};this.postWithCredentials=function(e,d,c){return b("POST",e,d,c,true)};this.request=b};window.XHR=XHR;ICanHas=function(a,b){return{cors:function(){var e=b.XDomainRequest||b.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest;if(e){e=new Boolean(e);e.withCredentials=!window.XDomainRequest}return e}(),orientation:window.orientation!==void 0,touch:"ontouchstart"in b,video:function(){var e=a.createElement("video"),d=!!e.canPlayType;if(d){d=new Boolean(d);d.vp6=e.canPlayType('video/x-flv; codecs="vp6"')||false;d.vp8=e.canPlayType('video/webm; codecs="vp8,vorbis"')||false;d.h264=
navigator.userAgent.toLowerCase().search("android")>-1?"probably":e.canPlayType('video/mp4; codecs="avc1.42E01E"')||e.canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"')||false}return d}()}}(document,window);FlashDetect=function(){var a=navigator,b=false,e=0,d=0,c=0,n=null,j=null;if(a.plugins&&a.plugins.length){if((a=a.plugins["Shockwave Flash"])&&a.description){n=a.description;
b=true}}else if(a.mimeTypes&&a.mimeTypes.length){if((a=a.mimeTypes["application/x-shockwave-flash"])&&a.enabledPlugin)b=true}else try{n=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version");b=true}catch(h){}if(n){j=n.replace(/\D+/g,".").replace(/^\./,"");a=j.split(".");e=parseInt(a[0],10);d=parseInt(a[1],10);c=parseInt(a[2],10)}return{installed:b,raw:n,version:j,major:e,minor:d,revision:c,versionAtLeast:function(o,q,p){o=o||10;q=q||0;p=p||0;var g=[e,d,c],t=arguments,w=Math.min(g.length,
t.length),r;for(r=0;r<w;r++)if(g[r]>=t[r]){if(!(r+1<w&&g[r]===t[r]))return true}else return false}}}();$m=
{};(function(a){function b(i,m,v){if(a.type(v)!=="array"||v===o)v=[v];for(var s=0,x=v.length;s<x;s++)v[s][i]||(v[s][i]=m);a[i]=function(){var u=Array.prototype.slice.call(arguments),O=u.shift();return m.apply(O,u)}}function e(i,m,v,s){v[i]=m;s.push(i);s.length>1E3&&delete v[s.shift()];return m}function d(i,m){if(i in m)return m[i];return false}function c(){var i=this.valueOf();return i<0?~~i-1:~~i}function n(i,m){return this<m?i>this?i:this:m}function j(i,m){var v=this.valueOf()+"";return Array(i-
v.length+1).join(m||"0")+v}if(!window.Element)window.Element={};for(var h=document,o=Array.prototype,q=!window.HTMLElement?{}:HTMLElement.prototype,p=!window.NodeList?{}:NodeList.prototype,g=Number.prototype,t=String.prototype,w=window,r={},z=[],A="Boolean Number String Function Array Date RegExp Object".split(" "),k=[],D=0,C=A.length;D<C;D++)k["[object "+A[D]+"]"]=A[D].toLowerCase();a.type=function(i){return i==null?String(i):k[Object.prototype.toString.call(i)]||"object"};a.isArray=function(i){return a.type(i)===
"array"};a.emptyFunction=function(){};a.clone=function(i){var m=a.isArray(i)?[]:{};for(D in i)if(D!=="clone")m[D]=i[D]&&a.type(i[D])==="object"?a.clone(i[D]):i[D];return m};a.addEventListener=function(i,m,v){window.addEventListener?i.addEventListener(m,v,false):i.attachEvent("on"+m,v)};a.removeEventListener=function(i,m,v){window.removeEventListener?i.removeEventListener(m,v,false):i.detachEvent("on"+m,v)};a.findKey=function(i,m){for(var v in m)if(m.hasOwnProperty(v)&&m[v]===i)return v;return false};
a.fibonacci=function(i){var m=Math.sqrt(5);return(1/m*Math.pow((1+m)/2,i)-1/m*Math.pow((1-m)/2,i)).round()};a.withinElement=function(i,m){var v=m.relatedTarget;try{if(v&&v!==document&&!v.parentNode)return true;for(;v&&v!==i;)v=v.parentNode;if(v!==i)return false}catch(s){}return true};b("abs",function(){var i=this.valueOf();return i<0?-i:i},g);b("addClass",function(i){if(this.length&&this.forEach)this.forEach(function(m){a.addClass(m,i)});else if(!a.hasClass(this,i))this.className=this.className.split(" ").concat(i).unique().join(" ").trim();
return this},[q,p]);b("attr",function(i,m){if(a.type(i)==="object"){for(prop in i)i[prop]===null||i[prop]===""?this.removeAttribute(prop):this.setAttribute(prop,i[prop]);return this}if(m===void 0)return this.getAttribute(i);m===null||m===""?this.removeAttribute(i):this.setAttribute(i,m);return this},q);b("ceil",function(){return c.call(this.valueOf()+1)},g);b("clamp",function(i,m,v){function s(){if(checkCount>200)return false;if(x.innerText!=i||x[property]==0){checkCount++;setTimeout(s,1)}else a:if(!(x[property]<=
v)){for(;x[property]>v;){x.innerText=x.innerText.substr(0,x.innerText.length-1);if(x.innerText==""||x.innerText.length==0)break a}x.innerText=x.innerText.substr(0,x.innerText.length-3)+"..."}}var x=this;x.innerHTML=i;property=m=="height"?"clientHeight":"clientWidth";checkCount=0;s();return x},q);b("clear",function(){this.childNodes.forEach(function(i){i.remove&&i.remove()});return this},q);b("computeStyle",function(i){if(!w.getComputedStyle)w.getComputedStyle=function(m){this.el=m;this.getPropertyValue=
function(v){var s=/(\-([a-z]){1})/g;if(v=="float")v="styleFloat";if(s.test(v))v=v.replace(s,function(x,u,O){return O.toUpperCase()});return m.currentStyle&&m.currentStyle[v]?m.currentStyle[v]:null};return this};return w.getComputedStyle(this,null).getPropertyValue(i)},q);b("contains",function(i){return this.indexOf(i)!==-1},[o,t]);b("css",function(i,m){if(a.type(i)==="object"){for(prop in i)this.style[prop]=i[prop];return this}if(m===void 0)return this.style[i];this.style[i]=m===null||m===""?"":m;
return this},q);b("floor",c,g);b("forEach",function(i,m){if(a.type(i)==="function")for(var v=this.length>>>0,s=0;s<v;s++)s in this&&i.call(m,this[s],s,this)},[o,p]);b("getElementsByClassName",function(i){var m=[],v=0,s,x,u;if(document.evaluate){s=".//*[contains(concat(' ', @class, ' '), ' "+i+" ')]";for(x=document.evaluate(s,this,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);u=x.snapshotItem(v++);)m[m.length]=u}else{s=RegExp("(^|\\s)"+i+"(\\s|$)");x=this.getElementsByTagName("*");v=0;for(var O=
x.length;v<O;v++){u=x[v];if(u.className===i||s.test(u.className))m[m.length]=u}}return m},h);b("hasAncestor",function(i){if(i===this)return true;for(var m=this.parentNode;m;){if(m===i)return true;m=m.parentNode}return false},q);b("hasClass",function(i){if(i.splice){for(var m=this.className.split(" "),v=0,s=m.length;v<s;v++)if(i.contains(m[v]))return true;return false}return RegExp("(?:^|\\s+)"+i+"(?:\\s+|$)").test(this.className)},q);b("hex2rgb",function(){if(cached=d(this,r))return cached;var i=
parseInt(this.replace("#",""),16);i=[(i&16711680)>>16,(i&65280)>>8,i&255];return e(this,"rgb("+i.join(",")+")",r,z)},t);b("html",function(i){if(i===void 0)return this.innerHTML;this.innerHTML=i;return this},q);b("indexOf",function(i){for(var m=0,v=this.length;m<v;m++)if(this[m]==i)return m;return-1},o);b("innerHeight",function(){for(var i=0,m,v=0,s=this.childNodes.length;v<s;v++){m=this.childNodes[v];if(m.style)i+=m.clientHeight+(a.toInt(a.computeStyle(m,"margin-top"),10)||0)+(a.toInt(a.computeStyle(m,
"margin-bottom",10))||0)}return i},q);b("limit",n,g);b("map",function(i,m){for(var v=this.length>>>0,s=Array(v),x=0;x<v;x++)if(x in this)s[x]=i.call(m,this[x],x,this);return s},o);b("max",function(){return Math.max.apply(Math,this)},o);b("min",function(){return Math.min.apply(Math,this)},o);b("pad",j,[t,g]);b("position",function(){var i=0,m=0,v=this;if(v.offsetParent){do{i+=v.offsetLeft;m+=v.offsetTop}while(v=v.offsetParent)}return{x:i,y:m}},q);b("prependChild",function(i){return this.insertBefore(i,
this.firstChild)},q);b("q",function(i){return this.querySelector(i)},[h,q]);b("qa",function(i){return this.querySelectorAll(i)},[h,q]);b("remove",function(){if(this.length)this.forEach(function(i){i.parentNode&&i.parentNode.removeChild(i)});else this.parentNode&&this.parentNode.removeChild(this)},[q,p]);b("removeClass",function(i){if(this.length&&this.forEach)this.forEach(function(m){a.removeClass(m,i)});else if(a.hasClass(this,i))this.className=this.className.replace(RegExp("(?:^|\\s+)"+i+"(?:\\s+|$)",
"g")," ").trim();return this},[q,p]);b("rgb2hex",function(){if(cached=d(this,r))return cached;var i=this.match(/\d{1,3}/g).slice(0,3);i=i.map(function(m){return j.call(n.call(parseInt(m,10),0,255).toString(16),2)});return e(this,i.join(""),r,z)},t);b("round",function(){return c.call(this.valueOf()+0.5)},g);b("toInt",function(i){return parseInt(this.valueOf?this.valueOf():this,i||10)},[t,g]);b("toFloat",function(i){return parseFloat(this.valueOf(),i||10)},[t,g]);b("trim",function(){return this.replace(/^\s\s*/,
"").replace(/\s\s*$/,"")},t);b("ucfirst",function(){return this.charAt(0).toUpperCase()+this.slice(1)},t);b("unique",function(){var i=[],m=0,v=this.length;a:for(;m<v;m++){for(var s=0,x=i.length;s<x;s++)if(i[s]===this[m])continue a;i[i.length]=this[m]}return i},o);b("wrap",function(i,m){var v=this,s=a.addClass(document.createElement(i),m||"");v.length||(v=Array(this));v.forEach(function(x,u){u===0&&x.parentNode.replaceChild(s,x);s.appendChild(x)});return s},[q,p])})($m);EventManager=function(){function a(d){if(!b[d]){var c=document.createElement("a");c.id="Event:"+d;e.appendChild(c);b[d]=c}return b[d]}var b={},e=document.createElement("div");e.id="events"+(new Date).getTime();document.body.appendChild(e);
this.bind=function(d,c){var n=a(d);window.addEventListener?n.addEventListener("click",c,false):n.attachEvent("onclick",c);return this};this.unbind=function(d,c){var n=a(d);window.removeEventListener?n.removeEventListener("click",c,false):n.detachEvent("onclick",c);return this};this.fire=function(d,c){var n,j=a(d);if(document.createEvent){n=document.createEvent("HTMLEvents");n.initEvent("click",false,true);n.name=d;n.data=c;return j.dispatchEvent(n)}else{try{c=JSON.stringify(c)}catch(h){}n=document.createEventObject();
n.name=d;n.data=c;return j.fireEvent("onclick",n)}}};window.EventManager=EventManager;var vb="ming",wb="moogaloop",kc="noplayer",Ac="nomobile",db="mobile",jc="touch",Mb="desktop",Nc="html",Mc="flash",ja="noplayer",ya="hd",Ta="sd",Pa="mobile",Pc=[ya,Ta,Pa],ld="pl_volume",Jc="hd_preference",md="scaling_preference",Hb="onwebkittransitionend"in window?"webkitTransitionEnd":"transitionEnd",Gb=8,nd=250,Kc=140,Lc=200,od=265;ja=200;var Ub=7,mc=1.5,Qc=2E3,Oc=1500,Ma=1,Qa=
2,Kb=3,ka=4,sa=5,La=6,$b=7,yb=8,gb=9,xc=10,zc=11,wc=12,yc=13,nc=14,bc=15,mb=16,Rc=17,qc=18,rc=19,cc=20,Sc=21,sc=22,tc=23,ia=24,wa=25,fb=26,Za=27,Zb=28,ma=29,Lb=30,Tc=31,Ga=32,nb=33,ob=34,Ra=35,vc=36,jb="loadProgress",kb="playProgress",ib="play",hb="pause",xb="finish",lb="seek",tb="ready",jd="error",lc="addEventListener()",Bc="removeEventListener()",qb="play()",pb="pause()",rb="seekTo()",sb="unload()",Ua="setColor()",bb="setLoop()",cb="setVolume()",Ia="getDuration()",Ha="getCurrentTime()",Va="getVolume()",
Cc="getColor()",zb="getLoop()",Dc="getVideoUrl()",Ec="getVideoEmbedCode()",$a="getVideoWidth()",ab="getVideoHeight()",Na="paused()",Aa="a",pd="bb",ac="aa",qd="ca",Sb="aq",hc="as",N="bn",Z="aj",pc="bi",Yb="ac",fd="h",gd="l",hd="m",id="n";ja="ag";ja="f";ja="c";ja="g";var Uc="ay",rd="o";ja="am";ja="cm";var Eb="x",Fb="w",Ib="z",Ya="q",Oa="k",Tb="v",Sa="j",gc="bk",ic="bd",ad="cq",bd="y",fc="cc",cd="at",dd="bh",eb="cb",ec="cz",sd="az",xa="b",Fc="h",Gc="ao";ja="cd";var Vc="i",td="bp",ud="ba",Vb="al";ja=
"da";var vd="ae",wd="m";ja="au";Ya="q";var xd="an",yd="ak",Ba="e",qa="d",Wb="ah",Xb="ck",oc="bv",Wc="bl",zd="p",Ad="videos",Bd="av",Ic="be",Wa="s",Cd="bo",Xc="bm",la="l",Hc="r",Dd="br",Yc="ai",Ed="ce",Zc="bx";ja="j";var ed="bu",kd="cj";if(window.$){$=$;$$=$$}var y=MingClass.extend({init:function(a,b,e){function d(){if(!ICanHas.video)return false;if(o.ie)return false;if(o.safari&&o.safari<4)return false;for(var q in c.config.video.files)if(ICanHas.video[q])return true;return false}var c=this,n=b.assets,j,h;j=navigator;
h=j.userAgent.toLowerCase();j=j.platform.toLowerCase();var o={webkit:"webkitAppearance"in document.documentElement.style?parseFloat(h.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):false,firefox:/firefox/.test(h)?h.replace(/^.*firefox\/(\d+\.\d+\.\d+).*$/,"$1"):false,safari:/safari/.test(h)?parseFloat(h.replace(/^.*version\/(\d+)\.(\d+)?.*$/,"$1.$2")):false,ie:navigator.appName=="Microsoft Internet Explorer",opera:window.opera&&{}.toString.call(window.opera)=="[object Opera]"||false,win:j?/win/.test(j):
/win/.test(h),mac:/mac/.test(j||h)?parseFloat(h.replace(/^.* ((\d+)(_|\.)?(\d+)?).*$/,"$2.$4")):false,linux:j?/linux/.test(j):/linux/.test(h),android:/android/.test(h)?parseFloat(h.replace(/^.* android (\d+)\.(\d+).*$/,"$1.$2")):false,playBook:/playbook/.test(h)};c.element=a;c.config=b.config;c.playerType=null;c.playerMode=null;c.playableFiles=null;c.thumbs=b.thumbs;c.api=false;c.ua=o;c.uniqueId=b.uniqueId;y.cookieDomain=c.config.request.cookie_domain;c.playerMode=function(){if(c.playerMode)return c.playerMode;
var q=Mb;if(Math.min(screen.width,screen.height)<=480||y.getCookie("test_mobiloop")=="1"||o.android&&o.android<3)q=db;else if(ICanHas.orientation)q=jc;return q}();c.playableFiles=function(){var q=c.config.video,p=q.files,g={hd:false,sd:false,mobile:false};for(var t in p)if(ICanHas.video[t]){if(c.playerMode===db){if($m.contains(p[t],Pa))g.mobile=t;else if(y.mobileCanPlaySD()&&$m.contains(p[t],Ta))g.sd=t;break}for(var w=0,r=p[t].length;w<r;w++){var z=p[t][w];if(z===ya&&!g.hd)g.hd=t;else if(z===Ta&&
!g.sd)g.sd=t;else if(z===Pa&&!g.mobile)g.mobile=t}}if(!c.config.security.hd_embed)g.hd=false;if(c.playerMode===jc)if(q.height*q.width>921600){P.info("Can't play HD version on iPad: too big");g.hd=false;c.config.video.hd=false}return g}();c.playerType=function(q){var p=kc;switch(q){case Mc:p=FlashDetect.installed&&FlashDetect.major>=10?wb:d()?vb:p;break;case Nc:p=c.playerMode!==db&&!c.playableFiles.hd&&!c.playableFiles.sd?FlashDetect.installed&&FlashDetect.major>=10?wb:c.playableFiles.mobile?vb:p:
d()?vb:FlashDetect.installed&&FlashDetect.major>=10?wb:p;break}if(c.playerMode===db&&!c.playableFiles.mobile){var g;a:{q=c.config.video.files;for(g in q)if($m.contains(q[g],Pa)){g=true;break a}g=false}p=g?kc:y.mobileCanPlaySD()&&c.playableFiles.sd?vb:Ac}return p}(c.config.user.preferences.html===1?Nc:Mc);h=c.playerType===wb?n.moogaloop:n.ming[c.playerMode].js;j=c.playerType===wb?[]:n.ming[c.playerMode].css;P.info("Player Type:",c.playerType);P.info("Player Mode:",c.playerMode,Math.min(screen.width,
screen.height));P.info("Screen Size:",screen.width,"x",screen.height);P.info("Can play:",ICanHas.video.h264?"h264":"");P.info("Playable Files:",c.playableFiles.hd?"hd":"",c.playableFiles.sd?"sd":"",c.playableFiles.mobile?"mobile":"");c.setThumb();$m.forEach(j,function(q){var p=document.createElement("link");$m.attr(p,{rel:"stylesheet",href:n.css_path+q+(!n.cache?(q.indexOf("?")>-1?"&":"?")+(new Date).getTime():"")});document.getElementsByTagName("head")[0].appendChild(p)});j=$LAB.setOptions({AlwaysPreserveOrder:true,
BasePath:n.js_path});n.cache||(h=$m.map(h,function(q){return q+(q.indexOf("?")>-1?"&":"?")+(new Date).getTime()}));j.script(h).wait(function(){c.api=new y.API(c.config);playerElement=a.getElementsByTagName("div")[0];$m.addClass(playerElement,c.playerType===wb?ed:Aa);c.player=new (c.playerType===wb?y.Moogaloop:c.playerType===kc||c.playerType===Ac?y.NoPlayer:y.Ming)(playerElement,b.options[c.playerType===Ac?kc:c.playerType],c);e&&e.call(c)});P.info("Reticulating splines...")},getConfig:function(){return this.config},
setConfig:function(a){this.config=a},setThumb:function(){var a=this.element.getElementsByTagName("div")[0].getElementsByTagName("div")[0].getElementsByTagName("div")[0],b=a.getAttribute("data-thumb"),e=this.thumbs[640],d=this.element.clientWidth;if(d>=900)e=this.thumbs[960];if(d>=1E3)e=this.thumbs[1280];this.config.video.thumbnail=e;if(b!==e&&this.playerType===vb){if(this.config.embed.autoplay===0||this.playerMode!==Mb)a.style.backgroundImage="url("+e+")";a.setAttribute("data-thumb",e)}}});y.setCookie=
function(a,b,e,d){var c=document.getElementById(fd),n="";e=e||87600;d=d||y.cookieDomain;if(c){document.getElementById(gd).value=a;document.getElementById(hd).value=b;document.getElementById(id).value=e;window.addEventListener("message",function(j){j.data=="refresh"&&y.xhrRefresh()},false);c.submit()}else{if(e){c=new Date;c.setTime(c.getTime()+e*60*60*1E3);n="; expires="+c.toGMTString()}d="; domain="+d;document.cookie=a+"="+b+n+"; path=/"+d}};y.getCookie=function(a){var b=document.cookie;a=a+"=";var e;
if(b&&b!==""){b=document.cookie.split(";");for(var d=0,c=b.length;d<c;d++){e=b[d].trim();if(e.indexOf(a)===0)return unescape(e.substr(a.length))}}return null};y.eatCookie=function(a){document.cookie=a+"=; expires=Thu, 01-Jan-70 00:00:01 GMT;"};y.xhrRefresh=function(){var a;(new XHR).get(document.location.href,function(b){a=document.getElementsByTagName("body")[0];a.innerHTML=b;$m.forEach(a.getElementsByTagName("script"),function(e){e.innerHTML&&(new Function(e.innerHTML)).call(window)})})};y.checkRatio=
function(a,b,e){if(!b)return false;e=e.video.width/e.video.height;var d=a.clientWidth/a.clientHeight;if(Math.abs(e-d)<0.02){$m.removeClass(a,Eb);$m.removeClass(a,Fb)}else if(d>e){$m.removeClass(a,Fb);$m.addClass(a,Eb)}else{$m.removeClass(a,Eb);$m.addClass(a,Fb)}$m.removeClass(b,N)};y.mobileCanPlaySD=function(){return window.devicePixelRatio>=2};if(!y.init)y.init={queue:[],loaderAdded:false,loader:function(){if(y.init.queue.length>0)if(screen.width===0||screen.height===0){P.warn("Screen size is 0, waiting 250ms to try again");
setTimeout(y.init.loader,250)}else y.init.queue.shift()()}};window.Player=y;
y.Moogaloop=MingClass.extend({init:function(a,b,e){function d(l,F,I){P.info("url: ",l);var W={server:k.request.vimeo_url,player_server:k.request.player_url,cdn_server:k.request.cdn_url,embed_location:k.request.referrer,force_embed:b.force_embed,force_info:b.force_info,moogaloop_type:ba,js_api:1,js_getConfig:b.ref_id+".getConfig",js_setConfig:b.ref_id+".setConfig",clip_id:k.video.id,fullscreen:1},ca={id:F.id,name:F.id,styleclass:Z};if(D.ie)l+=(l.indexOf("?")>0?"&":"?")+"time="+(new Date).getTime();
for(var H in I)if(I.hasOwnProperty(H))W[H]=I[H];swfobject.embedSWF(l,F.id,"100%","100%","10.0.0","/assets/flash/expressInstall.swf",W,{allowscriptaccess:"always",allowfullscreen:"true",scalemode:"noscale",quality:"high",wmode:"opaque",bgcolor:"#000000"},ca,function(L){if(D.safari&&D.win){P.debug("Removing invisible from swfobject");$m.removeClass(L.ref,Z)}D.android&&D.android<2.2&&$m.removeClass(L.ref,Z);setTimeout(function(){if($m.hasClass(F,Wa))return l.indexOf(v)===0?A.loverLoaded():A.moogaloopLoaded();
else if(B&&$m.hasClass(B,Z))return l.indexOf(v)===0?A.loverThumbLoaded(true):A.moogaloopThumbLoaded(true)},2E3)})}function c(){setTimeout(function(){m.fire(tb)},0)}function n(){var l="cover"+e.uniqueId;O=document.getElementById(l);if(!O){O=document.createElement("div");O.setAttribute("id",l);$m.addClass(O,kd);a.appendChild(O)}d(v,O,{js_onLoad:b.ref_id+".player.loverLoaded",js_onThumbLoaded:b.ref_id+".player.loverThumbLoaded",js_setupMoog:b.ref_id+".player.loverInitiated"});k.embed.autoplay=1}function j(){var l=
"player"+e.uniqueId;fa=document.getElementById(l);if(!fa){fa=document.createElement("div");fa.setAttribute("id",l);a.appendChild(fa)}d(s,fa,{js_onLoad:b.ref_id+".player.moogaloopLoaded",js_onThumbLoaded:b.ref_id+".player.moogaloopThumbLoaded"})}function h(){B&&B.api_pause()}function o(){if(X)A.loverInitiated();else B&&B.api_play()}function q(l){B&&B.api_seekTo(l.data)}function p(){B&&B.api_unload()}function g(l){k.embed.color=l.data;B&&B.api_changeColor(l.data)}function t(l){k.embed.loop=!!l.data;
B&&B.api_setLoop(k.embed.loop)}function w(l){if(B){l=l.data;if(k.embed.api.version<2)l*=100;B.api_setVolume(l)}}function r(l){var F=false;switch(l.name){case Ha:F=B?B.api_getCurrentTime().toFixed(3):0;break;case Ia:F=B?B.api_getDuration().toFixed(3):k.video.duration;break;case Va:F=B?B.api_getVolume().toFixed(3):k.user.preferences.volume/100;break;case Na:F=B?!!B.api_paused():true;break}i.sendBack(l.name,F)}function z(l){try{l.data=JSON.parse(l.data)}catch(F){}var I=k.embed.api.version<2?l.data:"on"+
l.data.ucfirst();if(B){B.api_addEventListener(l.data,b.ref_id+".player."+I);P.debug("Adding listener",l.data,b.ref_id+".player."+I)}else{P.debug("Queuing listener",l.data,b.ref_id+".player."+I);x.push(["addEventListener",l.data,b.ref_id+".player."+I])}}P.info("Options:",b);P.info("Config:",e.config);var A=this,k=e.config,D=e.ua,C=e.playerMode===jc?Mb:e.playerMode,i=e.api,m=i.events,v=b.swfs.cover[C],s=b.swfs.player[C],x=[],u,O,fa,X,B,ba=(C===db?"mobi":"mooga")+"loop"+(k.embed.on_site?"_local":"");
A.config=k;P.info("swfUrl: ",s,"playerMode: ",C);k.embed.api.on&&m.bind(pb,h).bind(qb,o).bind(rb,q).bind(sb,p).bind(Ua,g).bind(bb,t).bind(cb,w).bind(Ha,r).bind(Ia,r).bind(Va,r).bind(Na,r).bind(lc,z);A.onProgress=function(l){m.fire(kb,l.toFloat().toFixed(3))};A.onPlayProgress=function(l){m.fire(kb,{seconds:l.seconds.toFloat().toFixed(3),percent:l.percent.toFloat().toFixed(3),duration:l.duration.toFloat().toFixed(3)})};A.onLoading=function(l){m.fire(jb,{bytes:l.bytesLoaded.toInt(),percent:l.percent.toFloat().toFixed(3)})};
A.onLoadProgress=function(l){m.fire(jb,{percent:l.percent.toFloat().toFixed(3),bytesLoaded:l.bytesLoaded.toInt(),bytesTotal:l.bytesTotal.toInt(),duration:l.duration.toFloat().toFixed(3)})};A.onPlay=function(){m.fire(ib)};A.onPause=function(){m.fire(hb)};A.onSeek=function(l){m.fire(lb,k.embed.api.version<2?l.toFloat().toFixed(3):{seconds:l.seconds.toFloat().toFixed(3),percent:l.percent.toFloat().toFixed(3),duration:l.duration.toFloat().toFixed(3)})};A.onFinish=function(){m.fire(xb)};A.loverLoaded=
function(){P.info("Lover loaded");$m.removeClass(a,Wa);X=document.getElementById("cover"+e.uniqueId);c();setTimeout(function(){if($m.hasClass(X,Z)){P.debug("Removing invisible from loaded timeout");A.loverThumbLoaded(true)}},Oc)};A.loverThumbLoaded=function(l){P.info("Lover thumbnail loaded?",l);if(!X){X=document.getElementById("cover"+e.uniqueId);c()}$m.removeClass(X,Z);$m.addClass(u,N)};A.loverInitiated=function(){P.debug("Lover play button clicked");j()};A.moogaloopLoaded=function(){$m.removeClass(a,
Wa);B=document.getElementById(b.ref_id);if(X){$m.remove(X);$m.removeClass(B,Z);X=null}else c();if(k.embed.api.on&&x.length>0)for(;x.length>0;){var l=x.shift(),F="api_"+l.shift();P.debug("Calling",F,"from queue",l);(new Function("this."+F+'("'+l.join('","')+'")')).call(B)}P.info("Welcome to Moogaloop!");setTimeout(function(){if($m.hasClass(B,Z)){P.debug("Removing invisible from loaded timeout");A.moogaloopThumbLoaded(true)}},Oc)};A.moogaloopThumbLoaded=function(l){P.info("Moog thumbnail loaded?",l);
B||(B=document.getElementById(b.ref_id));$m.removeClass(B,Z);$m.addClass(u,N)};A.destroy=function(){k.embed.api.on&&m.unbind(pb,h).unbind(qb,o).unbind(rb,q).unbind(sb,p).unbind(Ua,g).unbind(bb,t).unbind(cb,w).unbind(Ha,r).unbind(Ia,r).unbind(Va,r)};for(u=a.getElementsByTagName("div")[0];u.nextSibling;)a.removeChild(u.nextSibling);!(k.embed.on_site||k.embed.autoplay||k.embed.api.on||D.opera||C===db||k.security.privacy==="password")?n():j();a.parentNode.api_seekTo=function(l){q({data:l})}}});y.NoPlayer=MingClass.extend({init:function(a,b,e){function d(){var w=Math.round(a.clientWidth/2-h.clientWidth/2),r=Math.round(a.clientHeight/
2-h.clientHeight/2);h.style.left=w+"px";h.style.top=r+"px"}function c(){function w(){if(r.styleSheet.rules.length){r.styleSheet.cssText+=t;return n()}setTimeout(w,100)}var r;r=document.createElement("link");r.rel="stylesheet";r.href=g;document.getElementsByTagName("head")[0].appendChild(r);w()}function n(){var w=["Uh Oh!","D&rsquo;Oh!","Aw fiddlesticks!","Jeepers!","Oh dear!","Ouch!","Zoinks!","Awww, snap!","Blast!","Curses!","ACK!","Aw shucks.","Major bummer.","Dag-nab-it!","Aargh!","Boo-hoo!","&iexcl;Ay caramba!"];
h.innerHTML='<div class="'+qa+' noplayer"><h1>'+w[Math.floor(Math.random()*w.length)]+'</h1><p>This video can&rsquo;t be played with your current setup. <br/>Please switch to a browser that provides native H.264 support</a> or install <a href="http://adobe.com/go/getflashplayer" target="_blank">Adobe Flash Player</a>.</p></div>';setTimeout(function(){j.show()},100)}var j=this,h=a.children[3],o=a.children[4],q,p=new XHR,g=b.css_path,t="."+Aa+"{background-color:black!important}."+Aa+" ."+Ba+"{text-align:center;font-size:1.5em;width:90%}a {color: #00adef}a:hover{color: #F75342}."+
Aa+" ."+Ba+" ."+qa+".noplayer p{line-height: 1.1em}";j.element=a;j.show=function(){var w=h.getElementsByTagName("div")[0];$m.removeClass(h,N);$m.removeClass(o,N);d();setTimeout(function(){$m.addClass(w,Xb);$m.addClass(a,qa)},10)};for(window.addEventListener?window.addEventListener("resize",d,false):window.attachEvent("onresize",d);h.previousSibling;){if(h.previousSibling.className===ac)break;a.removeChild(h.previousSibling)}$m.removeClass(a,Wa);(function(){e.ua.ie&&e.config.embed.on_site?c():p.get(g,
function(w){q=w+t;w=document.createElement("style");if(e.ua.ie){w.type="text/css";w.styleSheet.cssText=q}else w.appendChild(document.createTextNode(q));document.getElementsByTagName("head")[0].appendChild(w);n()})})()}});
y.API=MingClass.extend({init:function(a){function b(k){if(!k||k==="")return false;try{return JSON.parse(k)}catch(D){var C={},i,m,v;k.split("&").forEach(function(s){i=s.split("=");m=decodeURIComponent(i[0]);v=decodeURIComponent(i[1]);if(m!=="id"){if(m==="params")m="value";if(v.contains(","))v=v.split(",")[0];C[m]=v}});return C}}function e(k){if($m.type(k)!=="string"){k=(k=k)||{};if(p)k.player_id=p;k.data==="undefined"&&delete k.data;if(q>1&&window.JSON)k=JSON.stringify(k);else{var D="method="+encodeURIComponent(k.method||
k.event)+"&params=",C=[];if(k.value)C.push(encodeURIComponent(k.value));else if($m.type(k.data)==="object")for(var i in k.data)C.push(encodeURIComponent(k.data[i]));else k.data&&k.data!=="undefined"&&C.push(encodeURIComponent(k.data));k.player_id&&C.push(k.player_id);k=D+C.join(",")}}window.parent.postMessage(k,h);P.debug("<- Sent",k)}function d(k){var D=k.name,C=k.data;try{C=JSON.parse(k.data)}catch(i){}if(q<2){D=$m.findKey(D,t);switch(D){case "onSeek":case "onProgress":C.percent&&delete C.percent;
case "onLoading":C.duration&&delete C.duration;break}}if(o[D]===true||k.name===tb)e({event:D,data:C})}function c(k){var D=b(k.data);k=D.method;var C=D.value;if(!D||!k)return false;if(k.substr(0,4)==="api_"){k=k.substr(4);k=z[k]||k;k=k.replace("()","")}D=k+"()";if(D===lc){o[C]=true;A.fire(lc,C);P.debug("-> Now listening for",C)}else if(D===Bc){o[C]=false;A.fire(Bc,C);P.debug("-> Stop listening for",C)}else if(w.contains(D)){P.debug("-> Received",k,C);switch(D){case cb:C=C.toFloat();if(q<2)C/=100;break;
case bb:C=!!C.toInt();break;case Ua:if(C.search(/^[A-Fa-f\d]+$/g)===-1||C.length!==3&&C.length!==6){P.warn("Invalid color value");return}break}A.fire(D,C)}else if(r.contains(D)){P.debug("-> Received request for",k,C);A.fire(D,C)}}function n(k){var D=false;switch(k.name){case Cc:D=a.embed.color;break;case Dc:D=a.video.url;break;case Ec:D=a.video.embed_code;break}j.sendBack(k.name,D)}if(!a.embed.api.on){this.events=new EventManager;return false}if(!window.postMessage||!window.parent.postMessage||window.location===
window.parent.location){P.warn("Player API unavailable because this browser does not support postMessage or is not loaded in an iframe.");a.embed.api.on=0;this.events=new EventManager;return false}var j=this,h=decodeURIComponent(a.request.referrer),o={},q=a.embed.api.version,p=a.embed.api.player_id,g=[jb,kb,ib,hb,xb,lb,tb,jd],t={onFinish:xb,onLoading:jb,onLoad:tb,onProgress:kb,onPlay:ib,onPause:hb,onSeek:lb},w=[lc,Bc,qb,pb,Ua,rb,bb,cb,sb],r=[Ia,Ha,Va,Cc,zb,Dc,Ec,$a,ab,Na],z={changeColor:Ua},A=new EventManager;
j.events=A;j.sendBack=function(k,D){k=k.replace("()","");if(q<2)k="api_"+k;e({method:k,value:D})};j.sendError=function(){P.error("API error")};j.destroy=function(){window.removeEventListener?window.removeEventListener("message",c,false):window.detachEvent("onmessage",c)};g.forEach(function(k){A.bind(k,d)});A.bind(Cc,n).bind(Dc,n).bind(Ec,n);window.addEventListener?window.addEventListener("message",c,false):window.attachEvent("onmessage",c)}});y.Stats=MingClass.extend({init:function(a,b){var e=b.playerType.ucfirst()+" "+b.playerMode.ucfirst(),d=window._gaq||[],c=null,n=b.playerType===vb?"local":"",j=(b.playerType===vb?"html5_"+b.playerMode:b.playerMode===db?"mobiloop":"moogaloop")+"_"+(a.embed.on_site?n:"embed");d.push(["pt._setAccount",a.analytics.ga_account]);this.clientLog=function(){var h=new XHR,o="//"+a.request.player_url+"/log/client",
q=["request_signature="+a.request.signature,"video="+ICanHas.video,"h264="+ICanHas.video.h264,"vp8="+ICanHas.video.vp8,"vp6="+ICanHas.video.vp6,"flash="+FlashDetect.version,"touch="+ICanHas.touch,"screen_width="+screen.width,"screen_height="+screen.height].join("&");h.post(o,q,function(){})};this.googleLog=function(h,o){o=parseInt(Number(o),10);if(isNaN(o))o=undefined;P.log("google analytics:",e,h,a.video.id,o);d.push(["pt._trackEvent",e,h,a.video.id+"",o])};this.partialPlayLog=function(h,o,q){h=
parseInt(h,10);if(h>c){var p=new XHR,g="//"+a.request.player_url+"/log/partial";o="request_signature="+a.request.signature+"&seconds="+h+"&quality="+o;P.log("vimeo stats:",h,"seconds played");q?p.post(g,o):p.post(g,o,function(){});c=h}};this.vimeoLog=function(h,o,q,p){var g=new XHR,t="//"+a.request.player_url+"/log/"+h+"/"+a.video.id,w="?embed_location="+a.request.referrer+"&request_signature="+a.request.signature;w+="&type="+j;if(o)w+="&quality="+o;if(q)w+="&percent="+q;P.log("vimeo stats:",h,o,
q);p?g.post(t,w):g.post(t,w,function(){})}}});if(!y.UI)y.UI={};y.UI.CanvasElement=MingClass.extend({init:function(a){if(!a)return false;this.element=a;this.origWidth=a.getAttribute("width");this.origHeight=a.getAttribute("height");this.width=this.origWidth*Gb;this.height=
this.origHeight*Gb},draw:function(a,b,e,d,c){this.setData(a).setTranslation(b).setScale(e).setColor(d).setShadow(c);this.refresh();return this},setData:function(a){this.data=a;return this},setTranslation:function(a){this.translation=a;return this},setScale:function(a){this.scale=a;return this},setColor:function(a){this.color=a;return this},setShadow:function(a){this.shadow=a;return this},refresh:function(){var a=this.data,b=this.shadow;try{if(!a||!this.element.getContext)return false}catch(e){return false}var d=
this.scale||1,c=this.translation?$m.clone(this.translation):{x:0,y:0},n=this.color||"ffffff";this.element.attr({width:this.width,height:this.height});d*=Gb;c.x*=Gb;c.y*=Gb;var j=this.element.getContext("2d"),h;j.clearRect(0,0,this.width,this.height);j.save();j.translate(c.x,c.y);j.scale(d,d);j.fillStyle=j.strokeStyle="#"+n;if(b){j.shadowOffsetX=j.shadowOffsetY=0;j.shadowBlur=10*Gb;j.shadowColor="rgba(0,0,0,0.5)"}d=0;for(c=a.length;d<c;d++)for(h in a[d])if(b=a[d][h])if($m.isArray(b))j[h].apply(j,b);
else j[h]=b;else j[h].apply(j);j.restore();return this}});